### ISSUE TITLE
Clean up file handling

### ISSUE THREAD

**Issue by iannesbitt** [PermafrostDiscoveryGateway/viz-points#2]
- [x] Send correct file paths to `las2las`
- [x] Remove files created at intermediate processing steps
- [x] Clean up archiving of original files

**Comment by iannesbitt** [comment]
Tests look ok. Still a problem where `os.rename(x, y)` outputs an error even though it completes the rename successfully:
```
2023-04-11T18:30:02:INFO: Archiving input file to /home/shares/drp/pointcloud/archive/Site7wgs84.las
Traceback (most recent call last):
  File "/home/nesbitt/miniconda3/envs/workflow/bin/tilepoints", line 8, in <module>
    sys.exit(cli())
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/pdgpoints/cli.py", line 42, in cli
    p.run()
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/pdgpoints/pipeline.py", line 65, in run
    lastools_iface.las2las(f=self.f,
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/pdgpoints/lastools_iface.py", line 161, in las2las
    os.rename(str(f), str(archive_fn))
FileNotFoundError: [Errno 2] No such file or directory: '/home/shares/drp/pointcloud/Site7wgs84.las' -> '/home/shares/drp/pointcloud/archive/Site7wgs84.las'
```
Perhaps a problem with python's interactions with the filesystem on `datateam`...
