### ISSUE TITLE
Solve or work around `py3dtiles.merger.merge` bug

### ISSUE THREAD

**Issue by iannesbitt** [PermafrostDiscoveryGateway/viz-points#4]
```
Traceback (most recent call last):
  File "/home/nesbitt/miniconda3/envs/workflow/bin/py3dtiles", line 8, in <module>
    sys.exit(main())
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/py3dtiles/command_line.py", line 31, in main
    merger.main(args)
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/py3dtiles/merger.py", line 331, in main
    return merge_from_files(
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/py3dtiles/merger.py", line 304, in merge_from_files
    tileset = merge_with_pnts_content(tilesets, relative_tileset_paths)
  File "/home/nesbitt/miniconda3/envs/workflow/lib/python3.9/site-packages/py3dtiles/merger.py", line 259, in merge_with_pnts_content
    raise RuntimeError("Result shouldn't be None")
RuntimeError: Result shouldn't be None
```

**Comment by iannesbitt** [comment]
Closing as "solved" because we probably won't be using this to merge singular tilesets, we will pretty much always have many
